spring:
  datasource:
    url: jdbc:h2:mem:teste
    username: teste
    password:
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    open-in-view: true
    show-sql: true
  devtools:
    add-properties: true
  flyway:
    enabled: false
logging:
  level:
    web: debug
