spring:
  datasource:
    username: postgres
    password: RafaDB
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://34.136.113.111:5432/rafa_db
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: postgresql
  flyway:
    enabled: false
  h2:
    console:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: rafa.tcc.umj@gmail.com
    password: rafatcc2021
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
logging:
  level:
    web: debug
