spring:
  datasource:
    username: rafa
    password: rafa
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://localhost:5432/rafa
  jpa:
    open-in-view: false
    database: postgresql
  flyway:
    enabled: false
  h2:
    console:
      enabled: false

logging:
  level:
    web: debug
