spring:
  datasource:
    username: postgres
    password: R4faDBase
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://150.136.80.100:5432/rafadb
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  flyway:
    enabled: false
  h2:
    console:
      enabled: false
logging:
  level:
    web: info
